In [4]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [5]:
arr1 = np.arange(9).reshape(3,3)

In [6]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [10]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])



In [12]:
ser1

T    0
U    1
V    2
dtype: int64

In [13]:
ser2

X    3
Y    4
dtype: int64

In [16]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [17]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [18]:
pd.concat([ser1,ser2],keys=['cat','cat2'])

cat   T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [19]:
dframe1= DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [20]:
dframe1

X         Y         Z
0 -1.199563  1.350209 -0.371145
1 -0.383544 -1.284094  0.935492
2 -0.299261 -0.486289  1.099871
3 -0.521358 -0.948664 -1.471006

In [21]:
dframe2

Y         Q         X
0  1.313851 -1.249397  0.772345
1 -0.551662 -0.831883  1.215005
2 -0.109066  0.821915 -0.633920

In [22]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -1.199563  1.350209 -0.371145       NaN
1 -0.383544 -1.284094  0.935492       NaN
2 -0.299261 -0.486289  1.099871       NaN
3 -0.521358 -0.948664 -1.471006       NaN
0  0.772345  1.313851       NaN -1.249397
1  1.215005 -0.551662       NaN -0.831883
2 -0.633920 -0.109066       NaN  0.821915

In [23]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0 -1.199563  1.350209 -0.371145       NaN
1 -0.383544 -1.284094  0.935492       NaN
2 -0.299261 -0.486289  1.099871       NaN
3 -0.521358 -0.948664 -1.471006       NaN
4  0.772345  1.313851       NaN -1.249397
5  1.215005 -0.551662       NaN -0.831883
6 -0.633920 -0.109066       NaN  0.821915

In [ ]:
# for mode info:visit concat pandas doc